# Generated by Django 3.0.5 on 2020-05-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='name',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
